import type { CatalogSnapshot } from "./catalog-types";

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

export const demoCredentials = {
  email: "admin@amkapps.com",
  password: "password",
};

export const seedSnapshot: CatalogSnapshot = {
  sessionUser: null,
  apps: [
    {
      id: "app-notes",
      slug: "amk-notes",
      name: "AMK Notes",
      shortDescription: "Fast note-taking with markdown support and cloud sync.",
      fullDescription: "AMK Notes helps you capture ideas quickly, organize them with tags, and keep your notes synced across devices.",
      iconUrl: "/icons/amk-notes.png",
      featured: true,
      isPublished: true,
    },
    {
      id: "app-calculator",
      slug: "amk-calculator",
      name: "AMK Calculator",
      shortDescription: "A clean scientific calculator for daily work.",
      fullDescription: "AMK Calculator includes scientific functions, history, and a lightweight interface built for quick calculations.",
      iconUrl: "/icons/amk-calculator.png",
      featured: true,
      isPublished: true,
    },
    {
      id: "app-cleaner",
      slug: "amk-cleaner",
      name: "AMK Cleaner",
      shortDescription: "Clean up junk files and reclaim storage space.",
      fullDescription: "AMK Cleaner scans for cache, duplicates, and temporary files so you can keep your device fast and tidy.",
      iconUrl: "/icons/amk-cleaner.png",
      featured: false,
      isPublished: true,
    },
    {
      id: "app-dictionary",
      slug: "amk-dictionary",
      name: "AMK Dictionary",
      shortDescription: "Offline-friendly dictionary and quick lookup tool.",
      fullDescription: "AMK Dictionary brings instant lookups, favorites, and a simple study workflow for everyday vocabulary needs.",
      iconUrl: "/icons/amk-dictionary.png",
      featured: false,
      isPublished: true,
    },
    {
      id: "app-weather",
      slug: "amk-weather",
      name: "AMK Weather",
      shortDescription: "Weather forecasts with simple alerts and radar.",
      fullDescription: "AMK Weather keeps forecasts, severe weather alerts, and quick summaries in one polished mobile-first experience.",
      iconUrl: "/icons/amk-weather.png",
      featured: true,
      isPublished: true,
    },
    {
      id: "app-dept-connect",
      slug: "department-connect",
      name: "Department Connect",
      shortDescription: "A communication hub for departments and teams.",
      fullDescription: "Department Connect streamlines announcements, resources, and team updates in a single app for campus or workplace use.",
      iconUrl: "/icons/department-connect.png",
      featured: true,
      isPublished: true,
    },
  ],
  versions: [
    {
      id: "ver-notes-140",
      appId: "app-notes",
      versionNumber: "1.4.0",
      apkUrl: "/downloads/sample.apk",
      fileSize: "28.4 MB",
      changelog: "Added nested folders\nImproved sync reliability\nPolished editor toolbar",
      releaseDate: daysAgo(3),
      isLatest: true,
      isPublished: true,
    },
    {
      id: "ver-notes-130",
      appId: "app-notes",
      versionNumber: "1.3.0",
      apkUrl: "/downloads/sample.apk",
      fileSize: "27.8 MB",
      changelog: "Better search\nBug fixes",
      releaseDate: daysAgo(24),
      isLatest: false,
      isPublished: true,
    },
    {
      id: "ver-calculator-210",
      appId: "app-calculator",
      versionNumber: "2.1.0",
      apkUrl: "/downloads/sample.apk",
      fileSize: "12.1 MB",
      changelog: "Scientific mode improvements\nMemory history",
      releaseDate: daysAgo(5),
      isLatest: true,
      isPublished: true,
    },
    {
      id: "ver-cleaner-180",
      appId: "app-cleaner",
      versionNumber: "1.8.0",
      apkUrl: "/downloads/sample.apk",
      fileSize: "18.6 MB",
      changelog: "New cleanup categories\nSafer preview before delete",
      releaseDate: daysAgo(9),
      isLatest: true,
      isPublished: true,
    },
    {
      id: "ver-dictionary-115",
      appId: "app-dictionary",
      versionNumber: "1.1.5",
      apkUrl: "/downloads/sample.apk",
      fileSize: "21.2 MB",
      changelog: "Expanded offline word list\nFaster lookup",
      releaseDate: daysAgo(12),
      isLatest: true,
      isPublished: true,
    },
    {
      id: "ver-weather-300",
      appId: "app-weather",
      versionNumber: "3.0.0",
      apkUrl: "/downloads/sample.apk",
      fileSize: "24.3 MB",
      changelog: "Radar cards\nImproved alerts\nBetter animations",
      releaseDate: daysAgo(2),
      isLatest: true,
      isPublished: true,
    },
    {
      id: "ver-dept-250",
      appId: "app-dept-connect",
      versionNumber: "2.5.0",
      apkUrl: "/downloads/sample.apk",
      fileSize: "31.0 MB",
      changelog: "Channels redesign\nPinned announcements\nFaster attachments",
      releaseDate: daysAgo(1),
      isLatest: true,
      isPublished: true,
    },
  ],
  screenshots: [
    { id: "shot-notes-1", appId: "app-notes", imageUrl: "/screenshots/amk-notes-1.png", sortOrder: 1 },
    { id: "shot-dept-1", appId: "app-dept-connect", imageUrl: "/screenshots/dept-connect-1.png", sortOrder: 1 },
    { id: "shot-dept-2", appId: "app-dept-connect", imageUrl: "/screenshots/dept-connect-2.png", sortOrder: 2 },
  ],
  downloads: [
    { id: "dl-1", appId: "app-notes", versionId: "ver-notes-140", downloadedAt: daysAgo(0.1), userAgent: "Chrome", userIp: "192.168.1.24" },
    { id: "dl-2", appId: "app-notes", versionId: "ver-notes-140", downloadedAt: daysAgo(0.4), userAgent: "Chrome", userIp: "192.168.1.25" },
    { id: "dl-3", appId: "app-calculator", versionId: "ver-calculator-210", downloadedAt: daysAgo(0.7), userAgent: "Chrome", userIp: "192.168.1.26" },
    { id: "dl-4", appId: "app-cleaner", versionId: "ver-cleaner-180", downloadedAt: daysAgo(1.2), userAgent: "Chrome", userIp: "192.168.1.27" },
    { id: "dl-5", appId: "app-weather", versionId: "ver-weather-300", downloadedAt: daysAgo(2.1), userAgent: "Chrome", userIp: "192.168.1.28" },
    { id: "dl-6", appId: "app-dept-connect", versionId: "ver-dept-250", downloadedAt: daysAgo(2.4), userAgent: "Chrome", userIp: "192.168.1.29" },
    { id: "dl-7", appId: "app-dept-connect", versionId: "ver-dept-250", downloadedAt: daysAgo(4.6), userAgent: "Chrome", userIp: "192.168.1.30" },
    { id: "dl-8", appId: "app-dictionary", versionId: "ver-dictionary-115", downloadedAt: daysAgo(6.8), userAgent: "Chrome", userIp: "192.168.1.31" },
  ],
};
