uploads = []
outputs = []

[[generated]]
id = "RiiNuSZ9LL_kDBmRtK-JI"
uri = "file://artifacts/app-portal/public/icons/department-connect.png"
type = "image"
title = "department-connect-icon"

[[generated]]
id = "Vff7e9jr4awUkaAx0NRGm"
uri = "file://artifacts/app-portal/public/icons/amk-notes.png"
type = "image"
title = "amk-notes-icon"

[[generated]]
id = "_6yNfG3sTx0ZfyRv4ZmuU"
uri = "file://artifacts/app-portal/public/icons/amk-cleaner.png"
type = "image"
title = "amk-cleaner-icon"

[[generated]]
id = "Qn7_J3kPpDjsTqMgzPOIy"
uri = "file://artifacts/app-portal/public/icons/amk-weather.png"
type = "image"
title = "amk-weather-icon"

[[generated]]
id = "FXuNck2hYbqAOY_xM897Q"
uri = "file://artifacts/app-portal/public/icons/amk-calculator.png"
type = "image"
title = "amk-calculator-icon"

[[generated]]
id = "4DwKTVxjP8v7zjOkyUT9Z"
uri = "file://artifacts/app-portal/public/icons/amk-dictionary.png"
type = "image"
title = "amk-dictionary-icon"

[[generated]]
id = "xXZyhF8obdurA2E5qOyTZ"
uri = "file://artifacts/app-portal/public/screenshots/dept-connect-1.png"
type = "image"
title = "department-connect-screenshot-1"

[[generated]]
id = "J3qanqSCkEK-x_tjPR8Up"
uri = "file://artifacts/app-portal/public/screenshots/dept-connect-2.png"
type = "image"
title = "department-connect-screenshot-2"

[[generated]]
id = "RGg6MKIVpVEf2D9rcfVfB"
uri = "file://artifacts/app-portal/public/screenshots/amk-notes-1.png"
type = "image"
title = "amk-notes-screenshot-1"

[[generated]]
id = "mdUA_BmcQxo3STmEC_OFM"
uri = "file://public/phone-mockup.png"
type = "image"
title = "phone-mockup-landing"
